Repository marcosdosea/eventos, pull requests merged in 2024-05, with the labels that each got.

#27 Implementado Back-end do manter subeventos
  Codigo/Evento/Core/Core.csproj
  Codigo/Evento/Core/DTO/SubeventoDTO.cs
  Codigo/Evento/Core/Service/ISubeventoService.cs
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/EventoWeb.csproj
  Codigo/Evento/EventoWeb/EventoWeb.csproj.user
  Codigo/Evento/EventoWeb/Mappers/SubeventoProfile.cs
  Codigo/Evento/EventoWeb/Mappers/TipoInscricaoProfile.cs
  Codigo/Evento/EventoWeb/Models/SubeventoModel.cs
  Codigo/Evento/EventoWeb/Program.cs
  Codigo/Evento/EventoWeb/Views/Subevento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
  Codigo/Evento/Service/SubeventoService.cs
Labels: enhancement

#33 Branch valdir santana #32 atualização no caso de uso mante eventos
  Codigo/Evento/Core/Service/IEventoService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Program.cs
Labels: bug

#38 Branch valdir santana #37 correção em manter eventos
  Codigo/Evento/Core/Service/IEventoService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/Service/EventoService.cs
  Codigo/Evento/Service/SubeventoService.cs
Labels: bug

#40 Criado os protótipos de alta fidelidade.
  Requisitos/Prototipos/UC05 T01 Gerenciar Evento list.png
  Requisitos/Prototipos/UC05 T02 Gerenciar Evento.png
  Requisitos/Prototipos/UC12 T01 Manter participantes.png
Labels: documentation

#43 Implemetação de Model, Controller, Mapper, Service e Views de Áreas d…
  Codigo/Evento/Core/Service/IAreaInteresseService.cs
  Codigo/Evento/EventoWeb/Controllers/AreaInteresseController.cs
  Codigo/Evento/EventoWeb/Mappers/AreainteresseProfile.cs
  Codigo/Evento/EventoWeb/Models/AreaInteresseModel.cs
  Codigo/Evento/EventoWeb/Program.cs
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Create.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Details.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Index.cshtml
  Codigo/Evento/Service/AreaInteresseService.cs
Labels: enhancement
