Repository marcosdosea/eventos, pull requests merged in 2024-07, with the labels that each got.

#134 Corrigido erros de compilação nos testes
  Codigo/Evento/EventoWeb/Controllers/ModelocrachaController.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaModel.cs
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/ModelocrachaControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/SubeventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/TipoInscricaoControllerTests.cs
  Codigo/Evento/ServiceTests/EventoServiceTests.cs
  Codigo/Evento/ServiceTests/SubeventoServiceTests.cs
  Codigo/Evento/ServiceTests/TipoInscricaoServiceTests.cs
Labels: bug

#146 Atualização do Front-End de Área de Interesse
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Create.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Index.cshtml
Labels: enhancement

#147 Implementado Testes de unidade de gestor do evento.
  Codigo/Evento/ServiceTests/EventoServiceTests.cs
Labels: enhancement

#148 Atualização de Front-End de Tipo de Inscrição
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
Labels: enhancement

#149 Atualização do Front-End de Subevento
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Views/Subevento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
Labels: enhancement

#152 Implementado Testes de Controller de gestor do evento.
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Evento/ServiceTests/PessoaServiceTests.cs
Labels: enhancement

#129 Header e footer ajustado
  Codigo/Evento/EventoWeb/Controllers/HomeController.cs
  Codigo/Evento/EventoWeb/Views/Home/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml.css
  Codigo/Evento/EventoWeb/wwwroot/css/_Layout_Inicio.css
  Codigo/Evento/EventoWeb/wwwroot/css/_header_footer.css
  Codigo/Evento/EventoWeb/wwwroot/css/site.css
  Codigo/Evento/EventoWeb/wwwroot/js/hamburguer.js
Labels: bug

#151 Atualização do Front-End de Evento
  Codigo/Evento/Core/Service/ITipoeventoService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Models/EventocreateModel.cs
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Delete.cshtml
  Codigo/Evento/Service/TipoeventoService.cs
Labels: enhancement

#156 Implementado teste de TipoeventoService
  Codigo/Evento/Service/TipoeventoService.cs
  Codigo/Evento/ServiceTests/TipoeventoServiceTests.cs
Labels: enhancement

#158 Implementado testes de EstadosbrasilService e resolvido error de compilação em EventoServiceTests
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/ServiceTests/EstadosbrasilServiceTests.cs
Labels: enhancement

#154 Correção Bag de Estados e validação e formatação de CPF e CEP na clas…
  Codigo/Evento/Core/Service/IPessoaService.cs
  Codigo/Evento/EventoWeb/Controllers/PessoaController.cs
  Codigo/Evento/EventoWeb/Models/PessoaCreateModel.cs
  Codigo/Evento/EventoWeb/Views/Pessoa/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Edit.cshtml
  Codigo/Evento/Service/PessoaService.cs
Labels: bug

#162 Resolvido error de compilação na classe PessoaControllerTests
  Codigo/Evento/EventoWebTests/Controllers/PessoaControllerTests.cs
Labels: bug

#164 Implementado testes de InscricaoService
  Codigo/Evento/ServiceTests/InscricaoServiceTests.cs
Labels: enhancement

#135 Update protótipos. Closes #133
  Requisitos/Prototipos/Área de Interesse Created.png
  Requisitos/Prototipos/Área de Interesse List.png
  Requisitos/Prototipos/Cadastrar Área de Interesse.png
  Requisitos/Prototipos/Index Área de Interesse - Delete.png
  Requisitos/Prototipos/UC01 T01 - Manter eventos - Excluir evento.png
  Requisitos/Prototipos/UC01 T01 - Manter eventos Delet.png
  Requisitos/Prototipos/UC01 T01 - Manter eventos listar.png
  Requisitos/Prototipos/UC01 T02 - Manter evento Inserir.png
  Requisitos/Prototipos/UC02 T01 - Cadastrar Gestor do Evento.png
  Requisitos/Prototipos/[Admin] UC01 T02 - Manter evento Created.png
  Requisitos/Prototipos/[Gestor] UC01 T02 - Manter evento Created.png
Labels: documentation

#163 Atualização tela Inicial
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/_Layout_Inicio.css
  Codigo/Evento/EventoWeb/wwwroot/css/_header_footer.css
Labels: bug

#165 Ajustar campos e models do front-end do projeto
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Models/SubeventoModel.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaoModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
Labels: bug

#168 Criar Front-End de Pessoa baseado no Design System
  Codigo/Evento/EventoWeb/Views/Pessoa/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Index.cshtml
Labels: enhancement

#180 update prototipos. Closes #174
  Requisitos/Prototipos/Área de Interesse Created.png
  Requisitos/Prototipos/Área de Interesse List.png
  Requisitos/Prototipos/Index Área de Interesse - Delete.png
  Requisitos/Prototipos/Tela Principal.png
  Requisitos/Prototipos/Tela de Login.png
  Requisitos/Prototipos/UC01 T01 - Manter eventos Delet.png
  Requisitos/Prototipos/UC01 T01 - Manter eventos listar.png
  Requisitos/Prototipos/UC02 T01 - Cadastrar Gestor do Evento.png
  Requisitos/Prototipos/UC04 T01 -  Manter Administradores Sistema.png
  Requisitos/Prototipos/UC04 T01 - Manter Administrador do Sistema.png
  Requisitos/Prototipos/UC05 T01 Gerenciar Evento list.png
  Requisitos/Prototipos/UC05 T02 Gerenciar Evento.png
  Requisitos/Prototipos/UC12 T01 Manter participantes.png
  Requisitos/Prototipos/[Admin] UC01 T02 - Manter evento Created.png
  Requisitos/Prototipos/[Admin] UC01 T02 - Manter evento Edit.png
  Requisitos/Prototipos/[Gestor] UC01 T02 - Manter evento Created.png
  Requisitos/Prototipos/Área de Interesse - Delete.png
  Requisitos/Prototipos/Área de Interesse Created.png
  Requisitos/Prototipos/Área de Interesse List.png
Labels: documentation

#167 Correção metodo gestão papel.
  Codigo/Evento/Core/Service/IEventoService.cs
  Codigo/Evento/Core/Service/IInscricaoService.cs
  Codigo/Evento/Core/Service/IPessoaService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Views/Evento/CreatePessoaPapel.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/Service/EventoService.cs
  Codigo/Evento/Service/InscricaoService.cs
  Codigo/Evento/Service/PessoaService.cs
  Codigo/Evento/ServiceTests/EventoServiceTests.cs
  Codigo/Evento/ServiceTests/InscricaoServiceTests.cs
  Codigo/Evento/ServiceTests/PessoaServiceTests.cs
Labels: bug

#184 Correção do bug Pessoa/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Edit.cshtml
Labels: bug

#182 Corrigido de bugs nos tests de controllers e service.
  Codigo/Evento/EventoWebTests/Controllers/AreaInteresseControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/SubeventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/TipoInscricaoControllerTests.cs
  Codigo/Evento/ServiceTests/EventoServiceTests.cs
  Codigo/Evento/ServiceTests/PessoaServiceTests.cs
Labels: bug

#185 Variação_Layout
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/_header_footer.css
  Codigo/Evento/EventoWeb/wwwroot/img/user.svg
Labels: enhancement

#187 Uptade front event page
  Codigo/Evento/EventoWeb/Views/Evento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Home/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
Labels: enhancement

#186 Implementar associação de Tipo Inscrição com Evento
  Codigo/Evento/Core/Service/ITipoInscricaoService.cs
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
  Codigo/Evento/Service/TipoInscricaoService.cs
Labels: enhancement

#170 Correção do menu bloquear o css do header e footer
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_menu.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/_Layout_Inicio.css
  Codigo/Evento/EventoWeb/wwwroot/css/_header_footer.css
  Codigo/Evento/EventoWeb/wwwroot/css/_menu.css
  Codigo/Evento/EventoWeb/wwwroot/js/menu_hamburguer.js
Labels: documentation

#179 Implementação 2 Telas Gerenciar evento e listar
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEventoListar.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/_gerenciareventolistar.css
  Codigo/Evento/EventoWeb/wwwroot/ícones/Colaboradores.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Evento.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Inscricoes.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Participantes.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Subeventos.png
Labels: enhancement

#196 Atualização da classe Subevento e criação da view e metodos CreateOrEdit
  Codigo/Evento/Core/DTO/SubeventoDTO.cs
  Codigo/Evento/Core/Service/ISubeventoService.cs
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Models/SubeventoCreateModel.cs
  Codigo/Evento/EventoWeb/Models/SubeventoModel.cs
  Codigo/Evento/EventoWeb/Models/SubeventocreateModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/CreateOrEdit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
  Codigo/Evento/Service/SubeventoService.cs
Labels: enhancement

#190 Ajuste de Campos para Tipo de Inscrição #189
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
Labels: bug

#200 Correções do front-end das telas do sistema (Versão Corrigida)
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Create.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Details.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreatePessoaPapel.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_menu.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Details.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
Labels: bug

#207 Resolvido erros de compilação no projeto de tests de controllers.
  Codigo/Evento/EventoWebTests/Controllers/SubeventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/TipoInscricaoControllerTests.cs
Labels: bug

#209 Atualização para View do Gerir Evento e Tipo Inscrição
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/CreatePessoaPapel.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEventoListar.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GestorEditarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
Labels: bug, enhancement

#212 Resolvido erro de compilação em ModelocrachaControllerTests e corrigido erros em Modelocracha
  Codigo/Evento/EventoWeb/Mappers/ModeloCrachaProfile.cs
  Codigo/Evento/EventoWeb/Views/Modelocracha/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Index.cshtml
  Codigo/Evento/EventoWebTests/Controllers/ModelocrachaControllerTests.cs
Labels: bug

#213 implementar manter tipos de inscrição subevento
  Codigo/Evento/Core/DTO/TipoInscricaoDTO.cs
  Codigo/Evento/Core/Service/ITipoInscricaoService.cs
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaoSubeventoModel.cs
  Codigo/Evento/EventoWeb/Views/Subevento/CreateOrEdit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/CreateTipoInscricaoSubevento.cshtml
  Codigo/Evento/EventoWebTests/Controllers/TipoInscricaoControllerTests.cs
  Codigo/Evento/Service/TipoInscricaoService.cs
Labels: enhancement

#220 Contiuanção do Desenvolvimento de Gerenciar Evento
  Codigo/Evento/Core/DTO/SubeventoDTO.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Models/GerenciarEventoModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEventoListar.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/CreateOrEdit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/_gerenciarevento.css
  Codigo/Evento/Service/SubeventoService.cs
Labels: enhancement

#216 Criado Front-End para Modelocracha.
  Codigo/Evento/Core/DTO/ModelocrachaDTO.cs
  Codigo/Evento/EventoWeb/Controllers/ModelocrachaController.cs
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Mappers/ModeloCrachaProfile.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaCreateModel.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Index.cshtml
  Codigo/Evento/EventoWebTests/Controllers/ModelocrachaControllerTests.cs
Labels: enhancement

#225 Update Menu
  Codigo/Evento/EventoWeb/Views/Pessoa/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_LayoutAdministrativo.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_menu.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/_header_footer.css
  Codigo/Evento/EventoWeb/wwwroot/css/_menu.css
  Codigo/Evento/EventoWeb/wwwroot/css/headerAndFooter.css
Labels: enhancement

#222 Front-end registrar, login e esqueceu a senha
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ForgotPassword.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
  Codigo/Evento/EventoWeb/wwwroot/img/LOGOTIPO.svg
Labels: enhancement
