Repository marcosdosea/eventos, pull requests merged in 2024-09, with the labels that each got.

#300 update list event
  Codigo/Evento/Core/Service/IEventoService.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/Service/EventoService.cs
Labels: enhancement

#298 Corrigido Post do Edit de Subevento Controller.
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Views/Evento/CreateParticipante.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/CreateOrEdit.cshtml
Labels: bug

#299 Implementar funcionalidade de criação de administrador - Frontend
  Codigo/Evento/Core/DTO/PessoaDTO.cs
  Codigo/Evento/Core/Service/IAdministradorService.cs
  Codigo/Evento/EventoWeb/Controllers/AdministradorController.cs
  Codigo/Evento/EventoWeb/Models/AdministradorModel.cs
  Codigo/Evento/EventoWeb/Models/PessoaModel.cs
  Codigo/Evento/EventoWeb/Views/Administrador/Create.cshtml
  Codigo/Evento/Service/AdministradorService.cs
Labels: enhancement

#306 Corrigir a associação da mesma pessoa ao mesmo papel, associação de p…
  Codigo/Evento/.idea/.idea.Evento/.idea/workspace.xml
  Codigo/Evento/Core/Pessoa.cs
  Codigo/Evento/Core/Service/IInscricaoService.cs
  Codigo/Evento/Core/Service/IPessoaService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Models/GestaoPapelModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/CreateColaborador.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreateGestor.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreateParticipante.cshtml
  Codigo/Evento/Service/InscricaoService.cs
  Codigo/Evento/Service/PessoaService.cs
Labels: enhancement

#302 Update pages
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/_ViewStart.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
Labels: bug

#290 Adição de inserts no dump de eventos-database.mwb
  AnaliseProjeto/Usúarios cadastrados no Dump.txt
  AnaliseProjeto/dump-evento-database.sql
Labels: documentation

#311 Add tela de registrar frequência
  Requisitos/Prototipos/Registrar Frequência.png
  Requisitos/Prototipos/UC05 T02 Gerenciar Evento.png
Labels: documentation

#312 Adicionar no banco da Itatechusers no CreatePessoa
  Codigo/Evento/Core/Service/IAdministradorService.cs
  Codigo/Evento/Core/Service/IPessoaService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/Service/AdministradorService.cs
  Codigo/Evento/Service/PessoaService.cs
Labels: enhancement
