Repository marcosdosea/eventos, pull requests merged in 2024-08, with the labels that each got.

#230 Implementado geração de Qrcode em Modelo Crachá.
  Codigo/Evento/EventoWeb/Controllers/ModelocrachaController.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaModel.cs
  Codigo/Evento/EventoWeb/Views/Modelocracha/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Index.cshtml
  Codigo/Evento/Util/QrCodeGenerator.cs
  Codigo/Evento/Util/Util.csproj
Labels: enhancement

#231 Implementação para campo de Vagas Disponíveis
  Codigo/Evento/Core/Service/IEventoService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/Service/EventoService.cs
Labels: bug

#233 Update table
  Codigo/Evento/EventoWeb/EventoWeb.csproj
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Index.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/_ViewStart.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/_ViewStart.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_LayoutAdministrativo.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/_ViewStart.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/_ViewStart.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/style.css
  Codigo/Evento/EventoWeb/wwwroot/lib/datatable/css/datatables.css
  Codigo/Evento/EventoWeb/wwwroot/lib/datatable/css/datatables.min.css
  Codigo/Evento/EventoWeb/wwwroot/lib/datatable/css/jquery.dataTables.min.css
  Codigo/Evento/EventoWeb/wwwroot/lib/datatable/js/datatables.js
  Codigo/Evento/EventoWeb/wwwroot/lib/datatable/js/datatables.min.js
  Codigo/Evento/EventoWeb/wwwroot/lib/datatable/js/pt-BR.json
Labels: enhancement

#242 Implementado validadores de tipo e tamanho de imagem.
  Codigo/Evento/EventoWeb/Controllers/ModelocrachaController.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaModel.cs
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/ModelocrachaControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/SubeventoControllerTests.cs
  Codigo/Evento/Util/ImagemUpload.cs
Labels: enhancement

#241 Update datatables
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreatePessoaPapel.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEventoListar.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/site.css
Labels: documentation

#243 Update Atalho Gerenciar Evento
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_LayoutAdministrativo.cshtml
  Codigo/Evento/EventoWeb/wwwroot/ícones/certificado.svg
  Codigo/Evento/EventoWeb/wwwroot/ícones/cracha.svg
Labels: enhancement

#247 Implementado logica do Qrcode em GerenciarEvento e corrigido telas em Modelocracha para se adaptar ao Evento
  Codigo/Evento/Core/Service/IInscricaoService.cs
  Codigo/Evento/Core/Service/IModelocrachaService.cs
  Codigo/Evento/EventoWeb/Controllers/ModelocrachaController.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaCreateModel.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Index.cshtml
  Codigo/Evento/EventoWebTests/Controllers/ModelocrachaControllerTests.cs
  Codigo/Evento/Service/InscricaoService.cs
  Codigo/Evento/Service/ModelocrachaService.cs
  Codigo/Evento/ServiceTests/SubeventoServiceTests.cs
Labels: bug, enhancement

#248 Implementação de Model States
  Codigo/Evento/EventoWeb/Controllers/AreaInteresseController.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Controllers/PessoaController.cs
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Models/SubeventoModel.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaoModel.cs
Labels: bug, enhancement

#250 Implementado separação de QrCodes por participante em modelo crachá.
  Codigo/Evento/EventoWeb/Controllers/ModelocrachaController.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/CreatePessoaPapel.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Index.cshtml
Labels: enhancement

#244 Adicionado campos em registrar
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
Labels: enhancement

#256 Front-End Revisado.
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreatePessoaPapel.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Index.cshtml
  Codigo/Evento/EventoWebTests/Controllers/AreaInteresseControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/ModelocrachaControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/SubeventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/TipoInscricaoControllerTests.cs
Labels: bug

#257 Implementado Imagem para Classe Pessoa.
  Codigo/Evento/EventoWeb/Controllers/PessoaController.cs
  Codigo/Evento/EventoWeb/Mappers/PessoaProfile.cs
  Codigo/Evento/EventoWeb/Models/PessoaModel.cs
  Codigo/Evento/EventoWeb/Views/Pessoa/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Edit.cshtml
Labels: enhancement

#261 Resolverido as multiplas áreas de interesse.
  Codigo/Evento/Core/Service/IEventoService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Mappers/EventoProfile.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/GestorEditarEvento.cshtml
  Codigo/Evento/Service/EventoService.cs
  Codigo/Evento/ServiceTests/EventoServiceTests.cs
Labels: bug

#262 Verificação de Models e Atualização
  Codigo/Evento/Core/Service/ITipoInscricaoService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Controllers/ModelocrachaController.cs
  Codigo/Evento/EventoWeb/Controllers/PessoaController.cs
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Models/EventocreateModel.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaCreateModel.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaModel.cs
  Codigo/Evento/EventoWeb/Models/PessoaCreateModel.cs
  Codigo/Evento/EventoWeb/Models/PessoaModel.cs
  Codigo/Evento/EventoWeb/Models/SubeventoCreateModel.cs
  Codigo/Evento/EventoWeb/Models/SubeventoModel.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaoModel.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaoSubeventoModel.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaocreateModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GestorEditarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Modelocracha/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/CreateOrEdit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/Service/TipoInscricaoService.cs
Labels: bug

#271 Implementar funcionalidade de criação de administrador - Backend e Injeção de depências do indentity
  Codigo/Evento/Core/Core.csproj
  Codigo/Evento/Core/IdentityContext.cs
  Codigo/Evento/Core/UsuarioIdentity.cs
  Codigo/Evento/EventoWeb/Models/PessoaModel.cs
  Codigo/Evento/EventoWeb/Views/Administrador/Create.cshtml
Labels: enhancement

#270 update register and login
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
Labels: enhancement

#272 Implementado Imagem para Classe Evento
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Mappers/EventoProfile.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/GestorEditarEvento.cshtml
  Codigo/Evento/Service/EventoService.cs
Labels: enhancement

#277 Reajuste backend gestão papel pessoa
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Models/GestaoPapelModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/CreateColaborador.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreateGestor.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreateParticipante.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
Labels: bug

#276 Implementar funcionalidade de criação de administrador - Backend e Injeção de depências do indentity
  Codigo/Evento/Core/Core.csproj
  Codigo/Evento/Core/DTO/PessoaDTO.cs
  Codigo/Evento/Core/IdentityContext.cs
  Codigo/Evento/Core/Service/IAdministradorService.cs
  Codigo/Evento/Core/Service/IPessoaService.cs
  Codigo/Evento/Core/UsuarioIdentity.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ConfirmEmailChange.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/LoginWith2fa.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/LoginWithRecoveryCode.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Logout.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Disable2fa.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Email.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/EnableAuthenticator.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/GenerateRecoveryCodes.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ResetAuthenticator.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/SetPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ShowRecoveryCodes.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/TwoFactorAuthentication.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ResendEmailConfirmation.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ResetPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/_ViewImports.cshtml
  Codigo/Evento/EventoWeb/Controllers/AdministradorController.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Controllers/PessoaController.cs
  Codigo/Evento/EventoWeb/Mappers/EventoProfile.cs
  Codigo/Evento/EventoWeb/Migrations/20240723164018_CreateIdentitySchema.Designer.cs
  Codigo/Evento/EventoWeb/Migrations/IdentityContextModelSnapshot.cs
  Codigo/Evento/EventoWeb/Models/AdministradorModel.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Models/GestaoPapelModel.cs
  Codigo/Evento/EventoWeb/Models/PessoaModel.cs
  Codigo/Evento/EventoWeb/Program.cs
  Codigo/Evento/EventoWeb/Views/Administrador/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreateColaborador.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreateParticipante.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/CreatePessoaPapel.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GerenciarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/GestorEditarEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_LoginPartial.cshtml
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Evento/Service/AdministradorService.cs
  Codigo/Evento/Service/EventoService.cs
  Codigo/Evento/Service/PessoaService.cs
Labels: enhancement

#280 Branch 253 - 217
  Codigo/Evento/Core/Core.csproj
  Codigo/Evento/Core/DTO/PessoaDTO.cs
  Codigo/Evento/Core/IdentityContext.cs
  Codigo/Evento/Core/Service/IAdministradorService.cs
  Codigo/Evento/Core/UsuarioIdentity.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ConfirmEmailChange.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/LoginWith2fa.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/LoginWithRecoveryCode.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Logout.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Disable2fa.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Email.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/EnableAuthenticator.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/GenerateRecoveryCodes.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ResetAuthenticator.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/SetPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ShowRecoveryCodes.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/TwoFactorAuthentication.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ResendEmailConfirmation.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ResetPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/_ViewImports.cshtml
  Codigo/Evento/EventoWeb/Controllers/AdministradorController.cs
  Codigo/Evento/EventoWeb/Migrations/20240723164018_CreateIdentitySchema.Designer.cs
  Codigo/Evento/EventoWeb/Migrations/IdentityContextModelSnapshot.cs
  Codigo/Evento/EventoWeb/Models/AdministradorModel.cs
  Codigo/Evento/EventoWeb/Models/PessoaModel.cs
  Codigo/Evento/EventoWeb/Program.cs
  Codigo/Evento/EventoWeb/Views/Administrador/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_LoginPartial.cshtml
  Codigo/Evento/Service/AdministradorService.cs
  Codigo/Evento/Service/PessoaService.cs
Labels: enhancement

#283 Update injeção de dependencia
  Codigo/Evento/Core/Core.csproj
  Codigo/Evento/Core/IdentityContext.cs
  Codigo/Evento/Core/UsuarioIdentity.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ConfirmEmailChange.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/LoginWith2fa.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/LoginWithRecoveryCode.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Logout.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Disable2fa.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Email.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/EnableAuthenticator.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/GenerateRecoveryCodes.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ResetAuthenticator.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/SetPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/ShowRecoveryCodes.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Manage/TwoFactorAuthentication.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ResendEmailConfirmation.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/Account/ResetPassword.cshtml.cs
  Codigo/Evento/EventoWeb/Areas/Identity/Pages/_ViewImports.cshtml
  Codigo/Evento/EventoWeb/Migrations/20240723164018_CreateIdentitySchema.Designer.cs
  Codigo/Evento/EventoWeb/Migrations/IdentityContextModelSnapshot.cs
  Codigo/Evento/EventoWeb/Program.cs
  Codigo/Evento/EventoWeb/Views/Shared/_LoginPartial.cshtml
Labels: bug

#285 Corrigido error de compilação no projeto webtests.
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/ModelocrachaControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/SubeventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/TipoInscricaoControllerTests.cs
Labels: bug

#286 Updating permissions
  Codigo/Evento/EventoWeb/Controllers/AreaInteresseController.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Controllers/ModelocrachaController.cs
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
Labels: enhancement

#289 Implementar funcionalidade de criação de administrador - Backend
  Codigo/Evento/Core/DTO/PessoaDTO.cs
  Codigo/Evento/Core/Service/IAdministradorService.cs
  Codigo/Evento/EventoWeb/Controllers/AdministradorController.cs
  Codigo/Evento/EventoWeb/Models/AdministradorModel.cs
  Codigo/Evento/EventoWeb/Program.cs
  Codigo/Evento/EventoWeb/Views/Administrador/Create.cshtml
  Codigo/Evento/Service/AdministradorService.cs
Labels: enhancement
