Repository marcosdosea/eventos, pull requests merged in 2024-06, with the labels that each got.

#48 Desenvolvimento das telas referentes a UC02 e UC04
  Requisitos/Prototipos/UC02 T01 - Cadastrar Gestor do Evento.png
  Requisitos/Prototipos/UC04 T01 -  Manter Administradores Sistema.png
Labels: documentation

#53 Implementado Testes de controller e service em áreas de interesse.
  Codigo/Evento/EventoWebTests/Controllers/AreaInteresseControllerTests.cs
  Codigo/Evento/ServiceTests/AreaInteresseServiceTests.cs
Labels: enhancement

#54 Implementação Backend Tipos de Inscrição
  Codigo/Evento/Core/DTO/TipoInscricaoDTO.cs
  Codigo/Evento/EventoWeb/Controllers/AreaInteresseController.cs
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Details.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
  Codigo/Evento/Service/TipoInscricaoService.cs
Labels: enhancement

#57 Correções Realizadas em SubeventoServiceTests
  Codigo/Evento/ServiceTests/SubeventoServiceTests.cs
Labels: bug

#58 Implementado Testes de unidade das controllers e services em manter tipos de inscrição.
  Codigo/Evento/EventoWebTests/Controllers/TipoInscricaoControllerTests.cs
  Codigo/Evento/ServiceTests/TipoInscricaoServiceTests.cs
Labels: enhancement

#49 Criação da tela principal
  Requisitos/Prototipos/Principal.png
Labels: documentation

#61 Atualização em Manter Eventos #60
  Codigo/Evento/Core/DTO/EventoDTO.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/Service/EventoService.cs
  Codigo/Evento/ServiceTests/EventoServiceTests.cs
Labels: enhancement

#64 Desenvolvimento Back-end do manter pessoa
  Codigo/Evento/Core/DTO/PessoaDTO.cs
  Codigo/Evento/Core/Service/IPessoaService.cs
  Codigo/Evento/EventoWeb/Controllers/PessoaController.cs
  Codigo/Evento/EventoWeb/Mappers/PessoaProfile.cs
  Codigo/Evento/EventoWeb/Models/PessoaModel.cs
  Codigo/Evento/EventoWeb/Program.cs
  Codigo/Evento/EventoWeb/Views/Pessoa/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Pessoa/Index.cshtml
  Codigo/Evento/Service/PessoaService.cs
Labels: enhancement

#66 Implementado testes de unidade de controller e service da classe pessoa.
  Codigo/Evento/EventoWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Evento/ServiceTests/PessoaServiceTests.cs
Labels: enhancement

#79 Desenvolvimento do Header e Footer
  Codigo/Evento/EventoWeb/EventoWeb.csproj
  Codigo/Evento/EventoWeb/Views/Home/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml.css
  Codigo/Evento/EventoWeb/wwwroot/css/site.css
  Codigo/Evento/EventoWeb/wwwroot/img/LOGOTIPO.png
Labels: enhancement

#65 Front-end criado da AreaInteresse.
  Codigo/Evento/EventoWeb/EventoWeb.csproj
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Create.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Details.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Index.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/site.css
  Codigo/Evento/EventoWeb/wwwroot/css/style.css
  Codigo/Evento/EventoWeb/wwwroot/lib/bootstrap/dist/css/bootstrap.css
Labels: enhancement

#88 Regularizada models.
  Codigo/Evento/EventoWeb/Models/AreaInteresseModel.cs
  Codigo/Evento/EventoWeb/Models/ModelocrachaModel.cs
  Codigo/Evento/EventoWeb/Models/PessoaModel.cs
  Codigo/Evento/EventoWeb/Models/SubeventoModel.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaoModel.cs
Labels: bug

#91 Atualizações para Manter Evento e Manter TipoInscricao#89
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaocreateModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Details.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
Labels: bug

#90 Modal delete criado
  Codigo/Evento/EventoWeb/EventoWeb.csproj
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_DeleteModal.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_Layout.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/style.css
Labels: enhancement

#94 Finalizado front manter Evento. Closes #25
  Codigo/Evento/Core/Service/ITipoeventoService.cs
  Codigo/Evento/EventoWeb/Controllers/EventoController.cs
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Models/EventocreateModel.cs
  Codigo/Evento/EventoWeb/Program.cs
  Codigo/Evento/EventoWeb/Views/Evento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Details.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_DeleteModal.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/style.css
  Codigo/Evento/Service/TipoeventoService.cs
Labels: enhancement

#99 Criação categoria e Carrossel
  Codigo/Evento/EventoWeb/Views/Home/Index.cshtml
  Codigo/Evento/EventoWeb/wwwroot/Imagens_Eventos/Evento-Cortela.png
  Codigo/Evento/EventoWeb/wwwroot/Imagens_Eventos/Evento-Djavan.png
  Codigo/Evento/EventoWeb/wwwroot/Imagens_Eventos/Evento-Semac.png
  Codigo/Evento/EventoWeb/wwwroot/css/_Layout_Inicio.css
  Codigo/Evento/EventoWeb/wwwroot/js/carrossel.js
  Codigo/Evento/EventoWeb/wwwroot/ícones/Culturais.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Palestras.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Religiosos.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Shows.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Stand-up.png
  Codigo/Evento/EventoWeb/wwwroot/ícones/Teatros.png
Labels: enhancement

#104 Branch nadianne #14 prottipos uc01 t01 e t02
  Requisitos/Prototipos/UC01 T01 - Manter eventos listar.png
  Requisitos/Prototipos/UC01 T02 - Manter evento Inserir.png
Labels: documentation

#105 Criado tela Crud Área de Interesse
  Requisitos/Prototipos/Cadastrar Área de Interesse.png
  Requisitos/Prototipos/UC01 T01 - Manter eventos - Excluir evento.png
  Requisitos/Prototipos/UC01 T01 - Manter eventos listar.png
  Requisitos/Prototipos/UC02 T01 - Cadastrar Gestor do Evento.png
  Requisitos/Prototipos/UC04 T01 - Manter Administrador do Sistema.png
  Requisitos/Prototipos/UC12 T01 Manter participantes.png
Labels: documentation

#103 Front Manter Gestor concluido
  Codigo/Evento/EventoWeb/Models/DeleteModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/CreateGestorEvento.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/Shared/_DeleteModal.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/site.css
Labels: enhancement

#110 Updates na Tela Inicial
  Codigo/Evento/EventoWeb/Views/Home/Index.cshtml
  Codigo/Evento/EventoWeb/wwwroot/css/_Layout_Inicio.css
Labels: enhancement

#106 Criar telas de Inserção,Edição e Excluir para Sub-Evento #22
  Codigo/Evento/Core/Service/IEventoService.cs
  Codigo/Evento/EventoWeb/Controllers/SubeventoController.cs
  Codigo/Evento/EventoWeb/Models/SubeventoModel.cs
  Codigo/Evento/EventoWeb/Models/SubeventocreateModel.cs
  Codigo/Evento/EventoWeb/Views/Subevento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
  Codigo/Evento/Service/EventoService.cs
Labels: enhancement

#113 Ajustes no front-end de Tipo de Inscrição
  Codigo/Evento/EventoWeb/Controllers/TipoInscricaoController.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaoModel.cs
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Delete.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Details.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
Labels: enhancement

#114 Uptdate front Manter evento.
  Codigo/Evento/EventoWeb/Models/EventoModel.cs
  Codigo/Evento/EventoWeb/Views/Evento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Evento/Index.cshtml
Labels: enhancement

#118 Ajustes para TipoInscricao e Subevento
  Codigo/Evento/EventoWeb/Models/SubeventoModel.cs
  Codigo/Evento/EventoWeb/Models/TipoInscricaoModel.cs
  Codigo/Evento/EventoWeb/Views/Subevento/Create.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/Subevento/Index.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Create.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Edit.cshtml
  Codigo/Evento/EventoWeb/Views/TipoInscricao/Index.cshtml
Labels: enhancement

#121 Atualização de Front-End Área de Interesse
  Codigo/Evento/EventoWeb/Views/AreaInteresse/Create.cshtml
Labels: enhancement

#119 Resolvido erros no projeto de tests de controller e service
  Codigo/Evento/EventoWeb/Controllers/IEstadoService.cs
  Codigo/Evento/EventoWebTests/Controllers/EventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/SubeventoControllerTests.cs
  Codigo/Evento/EventoWebTests/Controllers/TipoInscricaoControllerTests.cs
  Codigo/Evento/ServiceTests/EventoServiceTests.cs
Labels: bug

#122 Front tela inicial
  Codigo/Evento/EventoWeb/Controllers/HomeController.cs
  Codigo/Evento/EventoWeb/Views/Home/Index.cshtml
  Codigo/Evento/EventoWeb/wwwroot/Imagens_Eventos/Evento-BoraLá.png
  Codigo/Evento/EventoWeb/wwwroot/Imagens_Eventos/Evento-Eletronica.png
  Codigo/Evento/EventoWeb/wwwroot/Imagens_Eventos/Evento-Jazz.png
  Codigo/Evento/EventoWeb/wwwroot/Imagens_Eventos/Evento-Rock.png
  Codigo/Evento/EventoWeb/wwwroot/Imagens_Eventos/Evento-Show.png
  Codigo/Evento/EventoWeb/wwwroot/css/_Layout_Inicio.css
Labels: enhancement
